# Generated by Django 4.1.3 on 2022-11-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_additionalfeature_product_on_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_image',
            field=models.ImageField(blank=True, upload_to='product/images/%Y/%m/%d/'),
        ),
    ]
