# Generated by Django 4.1.3 on 2022-11-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_second_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='second_image',
            new_name='detail_image',
        ),
    ]
