# Generated by Django 4.1.3 on 2022-11-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_second_image_product_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_image',
            field=models.ImageField(blank=True, upload_to='product/product/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='product/product/images//%Y/%m/%d/'),
        ),
    ]
