# Generated by Django 4.1.3 on 2022-11-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_detail_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_image',
            field=models.ImageField(blank=True, upload_to='product/company/images/%Y/%m/%d/'),
        ),
    ]
