# Generated by Django 4.1.3 on 2022-11-18 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 11, 18, 23, 33, 2, 205769, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
