# Generated by Django 4.1.3 on 2022-11-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='on_sale_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
