# Generated by Django 4.1.3 on 2022-11-21 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_company_description_alter_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
