# Generated by Django 4.1.3 on 2022-11-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_company_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='rating',
        ),
    ]
