# Generated by Django 3.2 on 2022-11-27 00:27

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_rename_comment_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
