# Generated by Django 3.2 on 2022-11-28 10:44

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_mycart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='markdown_desc',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
