# Generated by Django 3.2 on 2022-11-29 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20221128_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyCart',
        ),
    ]
