# Generated by Django 3.2 on 2022-11-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='t_price',
            field=models.IntegerField(default=1),
        ),
    ]
