# Generated by Django 3.2 on 2022-11-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_cartitem_t_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='t_price',
            field=models.IntegerField(default=1),
        ),
    ]
