# Generated by Django 3.2 on 2022-11-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_cart_t_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='t_price',
        ),
    ]
