# Generated by Django 3.2 on 2022-11-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_remove_cart_t_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='t_price',
        ),
    ]
