# Generated by Django 3.2 on 2022-11-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_cartitem_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
