# Generated by Django 3.2 on 2022-12-05 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20221205_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.review'),
        ),
    ]
