# Generated by Django 3.2 on 2022-12-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_review_parent_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='parent_comment',
            new_name='parent_review',
        ),
    ]
